Repository ArtalkJS/Artalk, pull requests merged in 2022-09, with the labels that each got.

#260 chore(deps): upgrade Vite to v3
  .circleci/config.yml
  .github/workflows/npm.yml
  .github/workflows/pages.yml
  package.json
  packages/artalk/vite.config.ts
  pnpm-lock.yaml
Labels: size/L

#261 refactor(api): moved http api functions to separate namespace
  packages/artalk-sidebar/src/components/page-list.ts
  packages/artalk-sidebar/src/components/site-list-floater.ts
  packages/artalk-sidebar/src/components/site-list.ts
  packages/artalk-sidebar/src/sidebar-views/pages-view.ts
  packages/artalk-sidebar/src/sidebar-views/sites-view.ts
  packages/artalk-sidebar/src/sidebar-views/transfer-view.ts
  packages/artalk/src/api/admin.ts
  packages/artalk/src/api/api-base.ts
  packages/artalk/src/api/captcha.ts
  packages/artalk/src/api/comment.ts
  packages/artalk/src/api/index.ts
  packages/artalk/src/api/page.ts
  packages/artalk/src/api/site.ts
  packages/artalk/src/api/system.ts
  packages/artalk/src/api/upload.ts
  packages/artalk/src/api/user.ts
  packages/artalk/src/artalk.ts
  packages/artalk/src/comment/actions.ts
  packages/artalk/src/editor/editor.ts
  packages/artalk/src/editor/plugs/header-input-plug.ts
  packages/artalk/src/editor/plugs/upload-plug.ts
  packages/artalk/src/layer/sidebar-layer.ts
  packages/artalk/src/lib/checker/admin-checker.ts
  packages/artalk/src/lib/checker/captcha-checker.ts
  packages/artalk/src/lib/stat.ts
  packages/artalk/src/list/list-lite.ts
  packages/artalk/src/list/list.ts
Labels: size/XL

#262 refactor: remove style importing from ts code file
  packages/artalk/src/comment/render.ts
  packages/artalk/src/components/pagination.ts
  packages/artalk/src/editor/editor.ts
  packages/artalk/src/layer/sidebar-layer.ts
  packages/artalk/src/list/list.ts
  packages/artalk/src/style/main.less
Labels: size/S

#266 add zh-TW
  packages/artalk/src/i18n/index.ts
Labels: size/M
