Repository ArtalkJS/Artalk, pull requests merged in 2022-07, with the labels that each got.

#217 fix: Address-relative path
  packages/artalk/src/comment/render.ts
Labels: size/XS

#218 Refactor on 2022-7-12
  packages/artalk/src/artalk.ts
  packages/artalk/src/comment/comment.ts
  packages/artalk/src/comment/render.ts
  packages/artalk/src/context.ts
  packages/artalk/src/i18n/index.ts
  packages/artalk/src/list/list-lite.ts
Labels: size/L

#219 refactor(list-lite): merge show/hide loading functions into setLoading
  packages/artalk/src/lib/ui.ts
  packages/artalk/src/list/list-lite.ts
Labels: size/M
