Repository ArtalkJS/Artalk, pull requests merged in 2023-09, with the labels that each got.

#563 fix(ui): fix plug cannot disable issue (#558)
  ui/packages/artalk/src/editor/plug-manager.ts
Labels: size/XS

#564 feat(config): support load env variables as config (#559)
  internal/config/base.go
Labels: size/S

#575 fix(captcha): image captcha base64 response issue
  server/handler/captcha.go
  server/middleware/limiter/limiter.go
Labels: size/XS

#566 doc(config): add info about env variables
  docs/guide/backend/config.md
Labels: size/S

#567 doc(extras): add deploy guide for railway.app
  docs/guide/extras.md
Labels: size/XS

#577 fix(cmd): remove app instance creation when mini boot
  cmd/admin.go
  cmd/base.go
  cmd/config.go
  cmd/export.go
  cmd/gen.go
  cmd/import.go
  cmd/server.go
  cmd/upgrade.go
  cmd/version.go
Labels: size/L

#578 perf(style): modify `z-index` less than 5
  ui/packages/artalk/src/style/comment.scss
  ui/packages/artalk/src/style/editor.scss
  ui/packages/artalk/src/style/list.scss
  ui/packages/artalk/src/style/main.scss
Labels: size/S

#585 refactor(renderer): abstract func of template renderer for multi-cases
  conf/artalk.example.simple.yml
  docs/guide/backend/email.md
  internal/core/service_email.go
  internal/core/service_notify.go
  internal/email/render.go
  internal/email/render_utils.go
  internal/notify_pusher/base.go
  internal/notify_pusher/multi.go
  internal/template/email_tpl/default.html
  internal/template/notify_tpl/default.html
  internal/template/render.go
  internal/template/render_test.go
  internal/template/strategy_email.go
  internal/template/strategy_notify.go
  internal/template/template_loader.go
  internal/template/template_render.go
  internal/template/template_test.go
Labels: size/XL

#586 perf(config): add error message for timezone setting
  internal/core/base.go
Labels: size/S

#587 feat(config): add `db.ssl` to enable db ssl mode
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  docs/guide/backend/config.md
  internal/config/config.go
  internal/db/dsn.go
  internal/db/dsn_test.go
Labels: size/M

#589 refactor(anti_spam): refactor anti_spam pkg and add unit test
  internal/anti_spam/base.go
  internal/anti_spam/base_test.go
  internal/anti_spam/checker.go
  internal/anti_spam/keywords.go
  internal/anti_spam/keywords_test.go
  internal/anti_spam/operate.go
  internal/core/service_anti_spam.go
  server/handler/comment_add.go
Labels: size/XL
