Repository ArtalkJS/Artalk, pull requests merged in 2023-12, with the labels that each got.

#661 fix(dark-mode): `setDarkMode` cannot save to instance config
  ui/packages/artalk/src/components/dark-mode.ts
  ui/packages/artalk/src/context.ts
  ui/packages/artalk/src/plugins/dark-mode.ts
  ui/packages/artalk/types/event.ts
Labels: size/M

#662 refactor(ui/layer): better layer implements and independence
  ui/packages/artalk/src/components/checker/index.ts
  ui/packages/artalk/src/layer/index.ts
  ui/packages/artalk/src/layer/layer-manager.ts
  ui/packages/artalk/src/layer/layer.ts
  ui/packages/artalk/src/layer/scrollbar-helper.ts
  ui/packages/artalk/src/layer/sidebar-layer.ts
  ui/packages/artalk/src/layer/wrap.ts
  ui/packages/artalk/src/plugins/admin-only-elem.ts
  ui/packages/artalk/src/service.ts
Labels: size/L

#663 fix(lifecycle): create multi-instances at the same time (#660)
  ui/packages/artalk/src/artalk.ts
  ui/packages/artalk/src/config.ts
  ui/packages/artalk/src/plugins/conf-remoter.ts
Labels: size/M

#664 fix(api/upload): `public_path` config enables the use of full url (#659)
  server/handler/img_upload.go
Labels: size/S

#665 docs(import): update the examples in import-framework.md
  docs/guide/frontend/import-blog.md
  docs/guide/frontend/import-framework.md
Labels: size/L

#656 feat: simple cache gc
  internal/cache/simple_cache/cache.go
  internal/cache/simple_cache/cache_test.go
Labels: size/M

#688 fix(ui/dark-mode): potential memory leak issue in auto mode
  ui/packages/artalk/src/components/dark-mode.ts
  ui/packages/artalk/src/plugins/dark-mode.ts
Labels: size/M

#684 chore: update description and fix typos
  README.en.md
  cmd/base.go
  docs/en/index.md
  docs/index.md
  docs/landing/src/components/Slogan.tsx
  ui/packages/artalk/README.md
  ui/packages/artalk/package.json
  ui/packages/artalk/src/artalk.ts
  ui/packages/artalk/src/list/layout.ts
  ui/packages/artalk/src/list/list.ts
  ui/packages/artalk/src/list/page.ts
  ui/packages/artalk/src/plugins/admin-only-elem.ts
  ui/packages/artalk/src/plugins/editor/header-user.ts
  ui/packages/artalk/src/plugins/editor/state-edit.ts
  ui/packages/artalk/src/plugins/editor/upload.ts
  ui/packages/artalk/src/plugins/list/fetch.ts
  ui/packages/artalk/src/plugins/list/reach-bottom.ts
  ui/packages/artalk/types/context.ts
  ui/packages/plugin-katex/main.ts
Labels: size/M

#691 chore: update readme
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.en.md
  README.md
Labels: size/M

#679 feat(ui): bump deps
  ui/.eslintrc.js
  ui/package.json
  ui/packages/artalk-sidebar/package.json
  ui/packages/artalk/.npmignore
  ui/packages/artalk/package.json
  ui/packages/artalk/postcss.config.js
  ui/packages/plugin-katex/package.json
  ui/packages/plugin-lightbox/package.json
  ui/pnpm-lock.yaml
Labels: size/XXL

#696 docs: fix redocly config
  docs/redocly.yaml
Labels: size/XS

#706 fix(ui/sidebar): refactor settings and fix save issue (#677)
  ui/packages/artalk-sidebar/src/components/PreferenceArr.vue
  ui/packages/artalk-sidebar/src/components/PreferenceGrp.vue
  ui/packages/artalk-sidebar/src/components/PreferenceItem.vue
  ui/packages/artalk-sidebar/src/lib/settings-option.ts
  ui/packages/artalk-sidebar/src/lib/settings.ts
  ui/packages/artalk-sidebar/src/pages/settings.vue
Labels: size/L

#707 fix(ui): add `referrerpolicy` attribute for iframe (#687)
  ui/packages/artalk-sidebar/index.html
  ui/packages/artalk/src/components/checker/captcha-renders.ts
  ui/packages/artalk/src/layer/sidebar-layer.ts
Labels: size/XS

#717 fix: don't mutate Default in-place
  ui/artalk/src/config.ts
Labels: size/XS
