Repository ArtalkJS/Artalk, pull requests merged in 2023-01, with the labels that each got.

#343 feat(i18n): add i18n support for backend
  Makefile
  artalk.example.simple.yml
  artalk.example.yml
  artalk.example.zh-CN.yml
  go.mod
  i18n/en.yml
  i18n/zh-CN.yml
  internal/config/config.go
  internal/core/core.go
  internal/i18n/gen/main.go
  internal/i18n/i18n.go
  main.go
  server/middleware/site_origin.go
Labels: size/L

#351 chore: revert the rename of image on dockerhub
  .github/workflows/docker.yml
  BACKEND.md
  README.en.md
  README.md
  docker-compose.yml
  docs/guide/backend/docker.md
  docs/guide/deploy.md
  scripts/docker-build.sh
Labels: size/M

#353 feat(i18n): add i18n support for sidebar
  .circleci/config.yml
  .github/workflows/release.yml
  cmd/admin.go
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  docs/guide/backend/build.md
  docs/guide/backend/config.md
  internal/core/conf_tpl.go
  internal/core/gen.go
  main.go
  server/common/conf.go
  server/handler/admin_setting.go
  server/server.go
  ui/packages/artalk-sidebar/auto-imports.d.ts
  ui/packages/artalk-sidebar/package.json
  ui/packages/artalk-sidebar/src/components/Header.vue
  ui/packages/artalk-sidebar/src/components/ItemTextEditor.vue
  ui/packages/artalk-sidebar/src/components/PageEditor.vue
  ui/packages/artalk-sidebar/src/components/SiteCreate.vue
  ui/packages/artalk-sidebar/src/components/SiteEditor.vue
  ui/packages/artalk-sidebar/src/components/SiteSwitcher.vue
  ui/packages/artalk-sidebar/src/components/Tab.vue
  ui/packages/artalk-sidebar/src/components/UserEditor.vue
  ui/packages/artalk-sidebar/src/global.ts
  ui/packages/artalk-sidebar/src/i18n/messages.ts
  ui/packages/artalk-sidebar/src/lib/settings.ts
  ui/packages/artalk-sidebar/src/main.ts
  ui/packages/artalk-sidebar/src/pages/comments.vue
  ui/packages/artalk-sidebar/src/pages/login.vue
  ui/packages/artalk-sidebar/src/pages/pages.vue
  ui/packages/artalk-sidebar/src/pages/settings.vue
  ui/packages/artalk-sidebar/src/pages/sites.vue
  ui/packages/artalk-sidebar/src/pages/transfer.vue
  ui/packages/artalk-sidebar/src/pages/users.vue
  ui/packages/artalk-sidebar/src/style/_extends.scss
  ui/packages/artalk-sidebar/vite.config.ts
  ui/packages/artalk/src/api/system.ts
  ui/packages/artalk/src/layer/sidebar-layer.ts
  ui/packages/artalk/src/list/list.ts
  ui/packages/artalk/src/style/main.less
  ui/pnpm-lock.yaml
Labels: size/XL

#358 refactor(CI): improve build and release workflows
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/build-app.yml
  .github/workflows/build-docker.yml
  .github/workflows/build-frontend.yml
  .github/workflows/docker.yml
  .github/workflows/npm.yml
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile
  docs/.vitepress/config.ts
  docs/.vitepress/theme/Artalk.vue
  docs/code/ArtalkCDN.json
  docs/code/ArtalkVersion.json
  docs/guide/deploy.md
Labels: size/XL

#360 docs: add open api
  .gitignore
  .vscode/tasks.json
  CONTRIBUTING.md
  Makefile
  README.en.md
  README.md
  conf/artalk.example.yml
  docs/.gitignore
  docs/develop/api-old.md
  docs/develop/api.md
  docs/develop/event.md
  docs/develop/index.md
  docs/package.json
  docs/pnpm-lock.yaml
  docs/redocly.yaml
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  go.sum
  server/common/conf.go
  server/handler/admin_cache.go
  server/handler/admin_comment_del.go
  server/handler/admin_comment_edit.go
  server/handler/admin_page_del.go
  server/handler/admin_page_edit.go
  server/handler/admin_page_fetch.go
  server/handler/admin_page_get.go
  server/handler/admin_send_mail.go
  server/handler/admin_setting.go
  server/handler/admin_site_add.go
  server/handler/admin_site_del.go
  server/handler/admin_site_edit.go
  server/handler/admin_site_get.go
  server/handler/admin_transfer.go
  server/handler/admin_user_add.go
  server/handler/admin_user_del.go
  server/handler/admin_user_edit.go
  server/handler/admin_user_get.go
  server/handler/admin_vote_sync.go
  server/handler/captcha.go
  server/handler/comment_add.go
  server/handler/comment_get.go
  server/handler/conf.go
  server/handler/img_upload.go
  server/handler/mark_read.go
  server/handler/pv.go
  server/handler/stat.go
  server/handler/user_get.go
  server/handler/user_login.go
  server/handler/user_logout.go
  server/handler/version.go
  server/handler/vote.go
  server/server.go
Labels: size/XXL

#361 fix: sidebar navigation sorting
  ui/packages/artalk-sidebar/src/pages/comments.vue
Labels: size/XS
