Repository ArtalkJS/Artalk, pull requests merged in 2023-02, with the labels that each got.

#364 docs: fix broken links
  docs/guide/frontend/config.md
Labels: size/S

#371 docs: fix wrong config value
  docs/guide/backend/fe-control.md
Labels: size/XS

#374 fix(email): email queue initialization issue
  internal/config/config.go
  internal/email/queue.go
  internal/notify_launcher/init.go
Labels: size/M

#375 fix(email): duplicate sending with multiple admins using same email addrs
  internal/notify_launcher/notify_launcher.go
Labels: size/XS

#426 feat: more functions to handle artalk lifecycle
  ui/packages/artalk/src/artalk.ts
  ui/packages/artalk/src/comment/comment.ts
  ui/packages/artalk/src/comment/render.ts
  ui/packages/artalk/src/config.ts
  ui/packages/artalk/src/context.ts
  ui/packages/artalk/src/editor/editor.ts
  ui/packages/artalk/src/editor/plugs/preview-plug.ts
  ui/packages/artalk/src/layer/index.ts
  ui/packages/artalk/src/layer/layer.ts
  ui/packages/artalk/src/lib/marked.ts
  ui/packages/artalk/src/lib/utils.ts
  ui/packages/artalk/src/service.ts
  ui/packages/artalk/types/artalk-data.d.ts
  ui/packages/artalk/types/context.d.ts
  ui/packages/artalk/types/global.d.ts
  ui/packages/plugin-katex/main.ts
  ui/packages/plugin-katex/package.json
Labels: size/XL

#425 fix: 为 docker 容器指定 restart=always 使得容器可以自动重启
  docs/guide/deploy.md
Labels: size/XS

#427 refactor(comment): seperate comment ui renders from single file
  ui/packages/artalk/src/comment/comment.ts
  ui/packages/artalk/src/comment/render-ctx.ts
  ui/packages/artalk/src/comment/render.ts
  ui/packages/artalk/src/comment/renders/actions.ts
  ui/packages/artalk/src/comment/renders/avatar.ts
  ui/packages/artalk/src/comment/renders/content.ts
  ui/packages/artalk/src/comment/renders/header.ts
  ui/packages/artalk/src/comment/renders/index.ts
  ui/packages/artalk/src/comment/renders/pending.ts
  ui/packages/artalk/src/comment/renders/reply-at.ts
  ui/packages/artalk/src/comment/renders/reply-to.ts
Labels: size/XL

#428 refactor(ui/checker): simplify checker lifecycle function param table
  ui/packages/artalk/src/lib/checker/admin-checker.ts
  ui/packages/artalk/src/lib/checker/admin.ts
  ui/packages/artalk/src/lib/checker/captcha-checker.ts
  ui/packages/artalk/src/lib/checker/captcha-renders.ts
  ui/packages/artalk/src/lib/checker/captcha.ts
  ui/packages/artalk/src/lib/checker/index.ts
Labels: size/L

#429 refactor(ui): automatic dependency injection
  ui/packages/artalk-sidebar/src/pages/comments.vue
  ui/packages/artalk/src/artalk.ts
  ui/packages/artalk/src/context.ts
  ui/packages/artalk/src/service.ts
  ui/packages/artalk/types/context.d.ts
Labels: size/L

#430 refactor(ui/dark-mode): separate dark mode logic into its own module
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  internal/query/testdata/example_site_conf.yml
  ui/packages/artalk-sidebar/src/assets/artalk.example.yml
  ui/packages/artalk/src/context.ts
  ui/packages/artalk/src/lib/dark-mode.ts
  ui/packages/artalk/src/service.ts
Labels: size/L

#434 refactor(ui/i18n): improve i18n function to standalone module
  ui/packages/artalk/src/context.ts
  ui/packages/artalk/src/i18n/index.ts
  ui/packages/artalk/src/service.ts
Labels: size/M

#435 refactor(ui/height-limit): modify height limit func to standalone module
  ui/.eslintrc.js
  ui/packages/artalk/src/comment/height-limit.ts
  ui/packages/artalk/src/comment/render.ts
Labels: size/L

#437 refactor(ui/list): modify list pagination to standalone module
  server/handler/comment_get_query.go
  ui/packages/artalk-sidebar/src/components/PreferenceGrp.vue
  ui/packages/artalk-sidebar/src/pages/comments.vue
  ui/packages/artalk/src/list/list-lite.ts
  ui/packages/artalk/src/list/list-ui.ts
  ui/packages/artalk/src/list/paginator/adaptors/index.ts
  ui/packages/artalk/src/list/paginator/adaptors/pagination.ts
  ui/packages/artalk/src/list/paginator/adaptors/read-more.ts
  ui/packages/artalk/src/list/paginator/holder.ts
  ui/packages/artalk/src/list/paginator/index.ts
Labels: size/L
