Repository ArtalkJS/Artalk, pull requests merged in 2024-06, with the labels that each got.

#912 perf(gravatar): support both sha256 and md5 hash algorithm for gravatar
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  docs/docs/.vitepress/theme/Artalk.vue
  docs/docs/guide/env.md
  docs/docs/guide/frontend/config.md
  internal/config/cache.go
  internal/config/utils.go
  internal/config/utils_test.go
  internal/core/base.go
  internal/dao/cook.go
  ui/artalk-sidebar/src/components/Header.vue
  ui/artalk-sidebar/src/stores/user.ts
  ui/artalk/src/defaults.ts
Labels: size/L

#913 Update fr.yml
  i18n/fr.yml
Labels: size/XS

#915 perf(ui/dev): bump eslint to v9
  .eslintignore
  .eslintrc.cjs
  .vscode/settings.json
  docs/landing/.eslintrc.cjs
  docs/landing/package.json
  docs/landing/tsconfig.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  ui/artalk-sidebar/.eslintrc.cjs
  ui/artalk-sidebar/package.json
  ui/artalk-sidebar/tsconfig.app.json
  ui/artalk-sidebar/tsconfig.json
  ui/artalk-sidebar/tsconfig.node.json
  ui/artalk-sidebar/tsconfig.vitest.json
  ui/artalk/.eslintrc.cjs
  ui/artalk/src/plugins/list/reach-bottom.ts
  ui/artalk/vite.config.ts
Labels: size/XXL

#923 refactor(ui/deps): remove `abortcontroller-polyfill`
  docs/docs/.vitepress/config.ts
  docs/docs/develop/compatibility.md
  eslint.config.mjs
  pnpm-lock.yaml
  ui/artalk/package.json
  ui/artalk/src/api/fetch.ts
Labels: size/S

#930 fix(plugin/lightbox): fix import for non-browser env
  docs/docs/.vitepress/config.ts
  docs/docs/.vitepress/theme/Artalk.vue
  docs/docs/guide/frontend/lightbox.md
  docs/docs/package.json
  pnpm-lock.yaml
  ui/plugin-lightbox/index.html
  ui/plugin-lightbox/main.ts
  ui/plugin-lightbox/package.json
  ui/plugin-lightbox/src/helper.ts
  ui/plugin-lightbox/src/main.ts
  ui/plugin-lightbox/tsconfig.json
  ui/plugin-lightbox/vite.config.ts
Labels: size/XL
