Repository ArtalkJS/Artalk, pull requests merged in 2024-03, with the labels that each got.

#797 French translation
  i18n/fr.yml
Labels: size/M

#793 更新案例页面链接
  docs/docs/guide/cases.md
  docs/docs/guide/extras.md
Labels: size/XS

#799 perf(db): optimize `N+1` query in comment list
  docker-entrypoint.sh
  internal/dao/cook.go
  internal/dao/migrate.go
  internal/dao/query_find.go
  internal/dao/query_find_test.go
  internal/entity/comment.go
  scripts/benchmark.sh
  server/handler/comment_create.go
  server/handler/comment_list.go
  server/handler/comments_get/base.go
  server/handler/comments_get/utils_list.go
  server/handler/stat.go
Labels: size/L
