Repository ArtalkJS/Artalk, pull requests merged in 2024-10, with the labels that each got.

#992 feat(config): enhance config file and data dir retrieval
  cmd/base.go
  go.mod
  go.sum
  internal/config/base.go
  internal/config/base_test.go
  internal/config/const.go
  internal/utils/fs.go
  internal/utils/fs_test.go
Labels: size/L

#996 refactor(ui/conf): introduce `DeepPartial` type for ui config
  ui/artalk/src/artalk.ts
  ui/artalk/src/config.ts
  ui/artalk/src/context.ts
  ui/artalk/src/defaults.ts
  ui/artalk/src/load.ts
  ui/artalk/src/types/config.ts
  ui/artalk/src/types/context.ts
  ui/plugin-kit/package.json
  ui/plugin-kit/src/plugin/main.ts
Labels: size/L

#997 refactor(api/vote): refactor vote http endpoint and logic
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  internal/dao/query_find.go
  server/handler/vote.go
  server/server.go
  ui/artalk/src/api/v2.ts
  ui/artalk/src/comment/actions.ts
Labels: size/L

#998 feat(api/vote): add get vote status endpoint
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  server/handler/base_test.go
  server/handler/vote.go
  server/handler/vote_test.go
  server/server.go
  test/fixtures/atk_votes.yml
  ui/artalk/src/api/v2.ts
Labels: size/XL

#983 feat(plugin/page_vote): add `page_vote` plugin
  docs/docs/.vitepress/config/en.ts
  docs/docs/.vitepress/config/zh.ts
  docs/docs/en/guide/frontend/config.md
  docs/docs/en/guide/frontend/voting.md
  docs/docs/zh/guide/frontend/config.md
  docs/docs/zh/guide/frontend/voting.md
  ui/artalk/index.html
  ui/artalk/src/config.ts
  ui/artalk/src/defaults.ts
  ui/artalk/src/plugins/index.ts
  ui/artalk/src/plugins/page-vote.ts
  ui/artalk/src/types/config.ts
Labels: size/L

#1006 feat(ui): add dependency injection container
  ui/artalk/src/lib/injection/container.test.ts
  ui/artalk/src/lib/injection/container.ts
  ui/artalk/src/lib/injection/index.ts
Labels: size/L

#1008 refactor(ui/sidebar): ensure compatibility with new client types
  ui/artalk-sidebar/auto-imports.d.ts
  ui/artalk-sidebar/src/artalk.ts
  ui/artalk-sidebar/src/components/PreferenceGrp.vue
  ui/artalk-sidebar/src/components/UserEditor.vue
  ui/artalk-sidebar/src/main.ts
  ui/artalk-sidebar/src/pages/comments.vue
  ui/artalk-sidebar/src/pages/login.vue
  ui/artalk-sidebar/src/pages/users.vue
  ui/artalk-sidebar/src/stores/user.ts
Labels: size/M

#1009 refactor(ui/auth): ensure compatibility with new client types
  ui/plugin-auth/DialogExample.tsx
  ui/plugin-auth/DialogMain.tsx
  ui/plugin-auth/DialogMethods.tsx
  ui/plugin-auth/DialogPageLogin.tsx
  ui/plugin-auth/DialogPageRegister.tsx
  ui/plugin-auth/EditorUser.tsx
  ui/plugin-auth/UserProfileDialog.tsx
  ui/plugin-auth/VerifyButton.tsx
  ui/plugin-auth/lib/layer.ts
  ui/plugin-auth/lib/methods.ts
  ui/plugin-auth/lib/oauth-login.ts
  ui/plugin-auth/lib/token-login.ts
  ui/plugin-auth/main.tsx
  ui/plugin-auth/merge/DialogMerge.tsx
  ui/plugin-auth/merge/DialogMergePageConfirm.tsx
  ui/plugin-auth/package.json
  ui/plugin-auth/types/context.d.ts
  ui/plugin-auth/types/index.d.ts
  ui/plugin-kit/src/plugin/main.ts
Labels: size/L

#1010 feat(ui/eslint): update `eslint-plugin-artalk` to v1.0.2
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  ui/eslint-plugin-artalk/README.md
  ui/eslint-plugin-artalk/package.json
  ui/eslint-plugin-artalk/src/artalk-plugin-checkers.ts
  ui/eslint-plugin-artalk/src/artalk-plugin.test.ts
  ui/eslint-plugin-artalk/src/artalk-plugin.ts
  ui/eslint-plugin-artalk/src/scc.ts
  vitest.workspace.ts
Labels: size/XL

#1011 feat(ui/conf): add `preferRemoteConf` option (#1000)
  docs/docs/en/guide/frontend/config.md
  docs/docs/zh/guide/frontend/config.md
  ui/artalk/index.html
  ui/artalk/src/defaults.ts
  ui/artalk/src/mount.ts
  ui/artalk/src/types/config.ts
Labels: size/M

#1012 chore(docs): corrected react usage example
  docs/docs/en/develop/import-framework.md
  docs/docs/zh/develop/import-framework.md
Labels: size/M
