Repository ArtalkJS/Artalk, pull requests merged in 2024-04, with the labels that each got.

#800 refactor(comments_get): reduce interface complexity by introducing `LiteDB`
  internal/dao/cook.go
  internal/dao/service.go
  internal/entity/comment.go
  internal/entity/page.go
  server/handler/comment_list.go
  server/handler/comments_get/base.go
  server/handler/comments_get/base_test.go
  server/handler/comments_get/expose.go
  server/handler/comments_get/lite_db.go
  server/handler/comments_get/scope_page.go
  server/handler/comments_get/scope_page_test.go
  server/handler/comments_get/scope_site.go
  server/handler/comments_get/scope_site_test.go
  server/handler/comments_get/scope_user.go
  server/handler/comments_get/scope_user_test.go
  server/handler/comments_get/scoper.go
  server/handler/comments_get/utils_count.go
  server/handler/comments_get/utils_list.go
  test/fixtures/comments.yml
Labels: size/XL

#817 perf(conf/upgit): disallow custom executable path of `upgit` for security
  .circleci/conditional_config.yml
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  docs/docs/guide/backend/img-upload.md
  docs/docs/guide/frontend/config.md
  docs/docs/guide/frontend/i18n.md
  server/handler/upload.go
Labels: size/M

#821 feat(artalk): add shorter export names
  .github/workflows/test-frontend.yml
  ui/artalk/package.json
Labels: size/M

#825 docs: format files and fix typos
  .prettierignore
  docs/docs/.vitepress/config.ts
  docs/docs/.vitepress/theme/Artalk.vue
  docs/docs/.vitepress/theme/Artransfer.vue
  docs/docs/.vitepress/theme/Layout.vue
  docs/docs/.vitepress/theme/index.ts
  docs/docs/.vitepress/theme/style.scss
  docs/docs/.vitepress/types/shims-vue.d.ts
  docs/docs/develop/api-old.md
  docs/docs/develop/event.md
  docs/docs/develop/fe-api.md
  docs/docs/develop/index.md
  docs/docs/develop/plugs.md
  docs/docs/guide/backend/admin_notify.md
  docs/docs/guide/backend/build.md
  docs/docs/guide/backend/captcha.md
  docs/docs/guide/backend/config.md
  docs/docs/guide/backend/daemon.md
  docs/docs/guide/backend/docker.md
  docs/docs/guide/backend/email.md
  docs/docs/guide/backend/fe-control.md
  docs/docs/guide/backend/img-upload.md
  docs/docs/guide/backend/moderator.md
  docs/docs/guide/backend/multi-site.md
  docs/docs/guide/backend/notify.md
  docs/docs/guide/backend/relative-path.md
  docs/docs/guide/backend/reverse-proxy.md
  docs/docs/guide/deploy.md
  docs/docs/guide/describe.md
  docs/docs/guide/extras.md
  docs/docs/guide/frontend/config.md
  docs/docs/guide/frontend/emoticons.md
  docs/docs/guide/frontend/i18n.md
  docs/docs/guide/frontend/import-blog.md
  docs/docs/guide/frontend/import-framework.md
  docs/docs/guide/frontend/ip-region.md
  docs/docs/guide/frontend/latex.md
  docs/docs/guide/frontend/lightbox.md
  docs/docs/guide/frontend/pv.md
  docs/docs/guide/intro.md
  docs/docs/guide/transfer.md
  docs/docs/tsconfig.json
Labels: size/XXL

#828 test: update test
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/fixtures/comments.yml
  test/fixtures/pages.yml
  test/ssg-test/.vitepress/config.mts
  test/ssg-test/.vitepress/theme/Artalk.vue
  test/ssg-test/.vitepress/theme/Footer.vue
  test/ssg-test/.vitepress/theme/Layout.vue
  test/ssg-test/.vitepress/theme/index.ts
  test/ssg-test/.vitepress/theme/style.css
  test/ssg-test/api-examples.md
  test/ssg-test/index.md
  test/ssg-test/package.json
  test/ssg-test/pnpm-lock.yaml
  test/testdata/example_site_conf.yml
  test/testdata/model_test_conf.yml
  test/vue-test/README.md
  test/vue-test/index.html
  test/vue-test/package.json
  test/vue-test/pnpm-lock.yaml
  test/vue-test/src/components/Artalk.vue
  test/vue-test/src/router/index.ts
  test/vue-test/vite.config.ts
Labels: size/XXL

#827 fix(i18n): fix fr locale and format
  .prettierignore
  i18n/en.yml
  i18n/fr.yml
  i18n/zh-CN.yml
  i18n/zh-TW.yml
Labels: size/XL

#836 添加新的扩展阅读文章与案例博客
  docs/docs/guide/cases.md
  docs/docs/guide/extras.md
Labels: size/XS

#838 fix(ui/comment): missing reply comment data when inserting
  ui/artalk/src/list/list.ts
Labels: size/XS
