Repository ArtalkJS/Artalk, pull requests merged in 2024-05, with the labels that each got.

#849 fix(ui/height_limit): height limit not working while loading images
  ui/artalk/src/comment/height-limit.ts
  ui/artalk/src/comment/render.ts
  ui/artalk/src/lib/utils.ts
Labels: size/M

#856 修复onBeforeUnmounted在 vue3 报错
  docs/docs/guide/frontend/import-framework.md
Labels: size/XS

#860 feat(ci): include frontend dist files in release
  .goreleaser.yml
  scripts/build-frontend.sh
Labels: size/S

#880 refactor(ui/stat): use class selector for pageview elements by default
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  docs/docs/guide/frontend/config.md
  docs/docs/guide/frontend/pv.md
  test/testdata/example_site_conf.yml
  ui/artalk/src/artalk.ts
  ui/artalk/src/comment/height-limit.ts
  ui/artalk/src/defaults.ts
  ui/artalk/src/plugins/stat.ts
  ui/artalk/src/types/config.ts
  ui/artalk/tests/stat-plugin.test.ts
Labels: size/L

#883 refactor(transfer): improve the reliability of the transfer
  cmd/import.go
  codecov.yml
  docs/docs/guide/transfer.md
  i18n/en.yml
  i18n/fr.yml
  i18n/jp.yml
  i18n/ko.yml
  i18n/ru.yml
  i18n/zh-CN.yml
  i18n/zh-TW.yml
  internal/artransfer/base.go
  internal/artransfer/base_test.go
  internal/artransfer/console.go
  internal/artransfer/console_test.go
  internal/artransfer/exporter.go
  internal/artransfer/importer.go
  internal/artransfer/importer_query.go
  internal/artransfer/importer_test.go
  internal/artransfer/json.go
  internal/artransfer/json_test.go
  internal/artransfer/print.go
  internal/artransfer/url_resolver.go
  internal/artransfer/url_resolver_test.go
  internal/artransfer/utils.go
  internal/dao/base.go
  internal/dao/cook.go
  internal/entity/artran.go
  internal/utils/string.go
  internal/utils/string_test.go
  server/handler/transfer_import.go
  test/fixtures/comments.yml
  ui/artalk-sidebar/src/components/LogTerminal.vue
Labels: size/XXL

#877 fix: close temp file
  server/handler/transfer_upload.go
Labels: size/XS

#884 refactor(dao): improve `QueryDBWithCache` func and concurrent unit tests
  internal/cache/action.go
  internal/cache/action_test.go
  internal/cache/base_test.go
  internal/dao/query_find.go
  internal/dao/query_find_create.go
  internal/dao/query_find_create_test.go
  test/testdata/model_test_conf.yml
Labels: size/L

#892 fix(conf_env): enhance environment variable loading for config
  Makefile
  conf/artalk.example.zh-CN.yml
  docs/docs/.vitepress/config.ts
  docs/docs/guide/backend/config.md
  docs/docs/guide/backend/docker.md
  docs/docs/guide/deploy.md
  docs/docs/guide/env.md
  docs/docs/guide/transfer.md
  go.mod
  go.sum
  i18n/en.yml
  i18n/fr.yml
  i18n/jp.yml
  i18n/ko.yml
  i18n/ru.yml
  i18n/zh-CN.yml
  i18n/zh-TW.yml
  internal/config/base.go
  internal/config/env_provider/provider.go
  internal/config/env_provider/provider_test.go
  internal/config/env_provider/unflatten.go
  internal/config/env_provider/unflatten_test.go
  internal/config/meta/gen/main.go
  internal/config/meta/mapping.go
  internal/config/meta/mapping_test.go
  internal/config/meta/meta.go
  internal/config/meta/meta_test.go
Labels: size/XXL

#893 chore(docs): add hexo-theme-solitude to cases.md
  docs/docs/guide/cases.md
Labels: size/XS

#904 feat(plugin_kit): add vite plugin for developing Artalk plugins
  pnpm-lock.yaml
  ui/artalk/src/artalk.ts
  ui/artalk/src/load.ts
  ui/plugin-kit/README.md
  ui/plugin-kit/client.d.ts
  ui/plugin-kit/package.json
  ui/plugin-kit/src/plugin/context.ts
  ui/plugin-kit/src/plugin/dev-page.ts
  ui/plugin-kit/src/plugin/dts.ts
  ui/plugin-kit/src/plugin/lint/export-lint.ts
  ui/plugin-kit/src/plugin/lint/index.ts
  ui/plugin-kit/src/plugin/lint/manifest-lint.ts
  ui/plugin-kit/src/plugin/lint/package-exports-lint.ts
  ui/plugin-kit/src/plugin/logger.ts
  ui/plugin-kit/src/plugin/main.ts
  ui/plugin-kit/src/plugin/runtime-helper.ts
  ui/plugin-kit/src/plugin/utils.ts
  ui/plugin-kit/src/runtime/main.ts
  ui/plugin-kit/src/types.d.ts
  ui/plugin-kit/tsconfig.json
  ui/plugin-kit/tsup.config.ts
Labels: size/XXL
