Repository ArtalkJS/Artalk, pull requests merged in 2024-01, with the labels that each got.

#747 docs: update multi-sites manual
  docs/docs/guide/backend/multi-site.md
  docs/docs/guide/deploy.md
  docs/docs/guide/frontend/sidebar.md
Labels: size/L

#750 fix(cache): unable to change admin list after caching (#748)
  internal/dao/query_find.go
  internal/dao/query_find_test.go
Labels: size/M

#752 refactor(ui/ctx): add `getComments` and `getCommentNodes` in context
  ui/artalk/src/context.ts
  ui/artalk/src/types/context.ts
  ui/plugin-lightbox/main.ts
Labels: size/M

#753 feat(ui/admin): add logout button in admin panel (#488)
  ui/artalk-sidebar/src/App.vue
  ui/artalk-sidebar/src/components/Header.vue
  ui/artalk-sidebar/src/components/SiteSwitcher.vue
  ui/artalk-sidebar/src/i18n/messages.ts
  ui/artalk-sidebar/src/pages/login.vue
  ui/artalk-sidebar/src/stores/user.ts
Labels: size/L

#734 fix: prevent propagation in editor
  ui/artalk/src/plugins/editor-kit.ts
Labels: size/XS

#754 feat(notify): add `notify_pending` config option (#728)
  conf/artalk.example.simple.yml
  conf/artalk.example.yml
  conf/artalk.example.zh-CN.yml
  docs/docs/guide/backend/admin_notify.md
  i18n/en.yml
  i18n/zh-CN.yml
  i18n/zh-TW.yml
  internal/config/config.go
  internal/notify_pusher/checker.go
  internal/notify_pusher/email.go
  internal/notify_pusher/multi.go
  internal/notify_pusher/operate.go
Labels: size/M

#755 perf(ui/conf): support for watching partial changes in config with `watchConf()`
  ui/artalk-sidebar/src/main.ts
  ui/artalk/src/context.ts
  ui/artalk/src/list/page.ts
  ui/artalk/src/plugins/dark-mode.ts
  ui/artalk/src/plugins/editor-kit.ts
  ui/artalk/src/plugins/editor/index.ts
  ui/artalk/src/plugins/list/copyright.ts
  ui/artalk/src/plugins/list/dropdown.ts
  ui/artalk/src/plugins/list/sidebar-btn.ts
  ui/artalk/src/plugins/list/unread-badge.ts
  ui/artalk/src/plugins/stat.ts
  ui/artalk/src/plugins/version-check.ts
  ui/artalk/src/service.ts
  ui/artalk/src/types/context.ts
  ui/artalk/src/types/event.ts
Labels: size/L
